name: nuts_and_bolts
description: Customize the nuts and bolts of your widgets. This package is nuts!
version: 0.1.0
author: Vince Varga <vince.varga@serial.dev>
homepage: https://github.com/dartsidedev/nuts_and_bolts
issue_tracker: https://github.com/dartsidedev/nuts_and_bolts/issues
documentation: https://pub.dev/documentation/nuts_and_bolts
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
