name: nuts_and_bolts
description: A new Flutter package project.
version: 0.2.0
author: Vince Varga <vince.varga@serial.dev>
homepage: https://github.com/dartsidedev/nuts_and_bolts
issue_tracker: https://github.com/dartsidedev/nuts_and_bolts/issues
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  nuts_activity_indicator: ^0.1.1
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
